INSTALL_TARGET_PROCESSES = SpringBoard

BUNDLE_NAME = CCVolumeMixer
CCVolumeMixer_BUNDLE_EXTENSION = bundle
CCVolumeMixer_FILES = CCVolumeMixer.m
CCVolumeMixer_CFLAGS = -fobjc-arc
CCVolumeMixer_PRIVATE_FRAMEWORKS = ControlCenterUIKit
CCVolumeMixer_INSTALL_PATH = /Library/ControlCenter/Bundles/

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
